<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
   xmlns:lib="http://findingaids.princeton.edu/pulfa/2/lib"
   xmlns:eac="urn:isbn:1-931666-33-4"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   exclude-result-prefixes="#all"
   version="2.0">


<xsl:variable name="lib:role-lookup" as="element()">
      <roles>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/act</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Actor</label>
            <code>act</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/adp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Adapter</label>
            <code>adp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/anl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Analyst</label>
            <code>anl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/anm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Animator</label>
            <code>anm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ann</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Annotator</label>
            <code>ann</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/app</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Applicant</label>
            <code>app</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/arc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Architect</label>
            <code>arc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/arr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Arranger</label>
            <code>arr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/acp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Art copyist</label>
            <code>acp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/art</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Artist</label>
            <code>art</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ard</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Artistic director</label>
            <code>ard</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/asg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Assignee</label>
            <code>asg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/asn</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Associated name</label>
            <code>asn</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/att</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Attributed name</label>
            <code>att</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/auc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Auctioneer</label>
            <code>auc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aut</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author</label>
            <code>aut</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aqt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author in quotations or text extracts</label>
            <code>aqt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aft</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author of afterword, colophon, etc.</label>
            <code>aft</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aud</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author of dialog</label>
            <code>aud</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aui</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author of introduction, etc.</label>
            <code>aui</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/aus</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Author of screenplay, etc.</label>
            <code>aus</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ant</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Bibliographic antecedent</label>
            <code>ant</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bnd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Binder</label>
            <code>bnd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bdd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Binding designer</label>
            <code>bdd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/blw</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Blurb writer</label>
            <code>blw</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bkd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Book designer</label>
            <code>bkd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bkp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Book producer</label>
            <code>bkp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bjd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Bookjacket designer</label>
            <code>bjd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bpd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Bookplate designer</label>
            <code>bpd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/bsl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Bookseller</label>
            <code>bsl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cll</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Calligrapher</label>
            <code>cll</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ctg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Cartographer</label>
            <code>ctg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cns</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Censor</label>
            <code>cns</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/chr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Choreographer</label>
            <code>chr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cng</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Cinematographer</label>
            <code>cng</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cli</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Client</label>
            <code>cli</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/clb</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Collaborator</label>
            <code>clb</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/col</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Collector</label>
            <code>col</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/clt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Collotyper</label>
            <code>clt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/clr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Colorist</label>
            <code>clr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cmm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Commentator</label>
            <code>cmm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cwt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Commentator for written text</label>
            <code>cwt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/com</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Compiler</label>
            <code>com</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cpl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Complainant</label>
            <code>cpl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cpt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Complainant-appellant</label>
            <code>cpt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cpe</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Complainant-appellee</label>
            <code>cpe</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cmp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Composer</label>
            <code>cmp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cmt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Compositor</label>
            <code>cmt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ccp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Conceptor</label>
            <code>ccp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cnd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Conductor</label>
            <code>cnd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/con</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Conservator</label>
            <code>con</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/csl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Consultant</label>
            <code>csl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/csp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Consultant to a project</label>
            <code>csp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cos</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestant</label>
            <code>cos</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cot</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestant-appellant</label>
            <code>cot</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/coe</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestant-appellee</label>
            <code>coe</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cts</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestee</label>
            <code>cts</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ctt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestee-appellant</label>
            <code>ctt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cte</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contestee-appellee</label>
            <code>cte</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ctr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contractor</label>
            <code>ctr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ctb</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Contributor</label>
            <code>ctb</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cpc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Copyright claimant</label>
            <code>cpc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cph</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Copyright holder</label>
            <code>cph</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/crr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Corrector</label>
            <code>crr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/crp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Correspondent</label>
            <code>crp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cst</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Costume designer</label>
            <code>cst</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cov</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Cover designer</label>
            <code>cov</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cre</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Creator</label>
            <code>cre</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/cur</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Curator of an exhibition</label>
            <code>cur</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dnc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Dancer</label>
            <code>dnc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dtc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Data contributor</label>
            <code>dtc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dtm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Data manager</label>
            <code>dtm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dte</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Dedicatee</label>
            <code>dte</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dto</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Dedicator</label>
            <code>dto</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dfd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Defendant</label>
            <code>dfd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dft</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Defendant-appellant</label>
            <code>dft</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dfe</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Defendant-appellee</label>
            <code>dfe</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dgg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Degree grantor</label>
            <code>dgg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dln</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Delineator</label>
            <code>dln</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dpc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Depicted</label>
            <code>dpc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dpt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Depositor</label>
            <code>dpt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dsr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Designer</label>
            <code>dsr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/drt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Director</label>
            <code>drt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dis</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Dissertant</label>
            <code>dis</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dbp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Distribution place</label>
            <code>dbp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dst</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Distributor</label>
            <code>dst</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dnr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Donor</label>
            <code>dnr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/drm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Draftsman</label>
            <code>drm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/dub</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Dubious author</label>
            <code>dub</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/edt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Editor</label>
            <code>edt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/elg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Electrician</label>
            <code>elg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/elt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Electrotyper</label>
            <code>elt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/eng</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Engineer</label>
            <code>eng</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/egr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Engraver</label>
            <code>egr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/etr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Etcher</label>
            <code>etr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/evp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Event place</label>
            <code>evp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/exp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Expert</label>
            <code>exp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/fac</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Facsimilist</label>
            <code>fac</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/fld</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Field director</label>
            <code>fld</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/flm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Film editor</label>
            <code>flm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/fpy</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>First party</label>
            <code>fpy</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/frg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Forger</label>
            <code>frg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/fmo</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Former owner</label>
            <code>fmo</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/fnd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Funder</label>
            <code>fnd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/gis</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Geographic information specialist</label>
            <code>gis</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/hnr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Honoree</label>
            <code>hnr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/hst</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Host</label>
            <code>hst</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ilu</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Illuminator</label>
            <code>ilu</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ill</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Illustrator</label>
            <code>ill</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ins</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Inscriber</label>
            <code>ins</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/itr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Instrumentalist</label>
            <code>itr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ive</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Interviewee</label>
            <code>ive</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ivr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Interviewer</label>
            <code>ivr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/inv</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Inventor</label>
            <code>inv</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lbr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Laboratory</label>
            <code>lbr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ldr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Laboratory director</label>
            <code>ldr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/led</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Lead</label>
            <code>led</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lsa</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Landscape architect</label>
            <code>lsa</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/len</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Lender</label>
            <code>len</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lil</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelant</label>
            <code>lil</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lit</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelant-appellant</label>
            <code>lit</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lie</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelant-appellee</label>
            <code>lie</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lel</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelee</label>
            <code>lel</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/let</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelee-appellant</label>
            <code>let</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lee</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Libelee-appellee</label>
            <code>lee</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lbt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Librettist</label>
            <code>lbt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lse</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Licensee</label>
            <code>lse</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lso</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Licensor</label>
            <code>lso</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lgd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Lighting designer</label>
            <code>lgd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ltg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Lithographer</label>
            <code>ltg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/lyr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Lyricist</label>
            <code>lyr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mfr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Manufacturer</label>
            <code>mfr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mrb</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Marbler</label>
            <code>mrb</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mrk</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Markup editor</label>
            <code>mrk</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mdc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Metadata contact</label>
            <code>mdc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mte</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Metal-engraver</label>
            <code>mte</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mod</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Moderator</label>
            <code>mod</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mon</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Monitor</label>
            <code>mon</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mcp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Music copyist</label>
            <code>mcp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/msd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Musical director</label>
            <code>msd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/mus</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Musician</label>
            <code>mus</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/nrt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Narrator</label>
            <code>nrt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/opn</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Opponent</label>
            <code>opn</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/orm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Organizer of meeting</label>
            <code>orm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/org</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Originator</label>
            <code>org</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/oth</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Other</label>
            <code>oth</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/own</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Owner</label>
            <code>own</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ppm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Papermaker</label>
            <code>ppm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pta</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Patent applicant</label>
            <code>pta</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pth</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Patent holder</label>
            <code>pth</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pat</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Patron</label>
            <code>pat</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prf</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Performer</label>
            <code>prf</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pma</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Permitting agency</label>
            <code>pma</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pht</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Photographer</label>
            <code>pht</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ptf</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Plaintiff</label>
            <code>ptf</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ptt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Plaintiff-appellant</label>
            <code>ptt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pte</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Plaintiff-appellee</label>
            <code>pte</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/plt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Platemaker</label>
            <code>plt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Printer</label>
            <code>prt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pop</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Printer of plates</label>
            <code>pop</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Printmaker</label>
            <code>prm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Process contact</label>
            <code>prc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pro</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Producer</label>
            <code>pro</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pmm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Production manager</label>
            <code>pmm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Production personnel</label>
            <code>prd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/prg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Programmer</label>
            <code>prg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pdr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Project director</label>
            <code>pdr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pfr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Proofreader</label>
            <code>pfr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pup</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Publication place</label>
            <code>pup</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pbl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Publisher</label>
            <code>pbl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/pbd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Publishing director</label>
            <code>pbd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ppt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Puppeteer</label>
            <code>ppt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rcp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Recipient</label>
            <code>rcp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rce</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Recording engineer</label>
            <code>rce</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/red</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Redactor</label>
            <code>red</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ren</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Renderer</label>
            <code>ren</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rpt</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Reporter</label>
            <code>rpt</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rps</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Repository</label>
            <code>rps</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rth</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Research team head</label>
            <code>rth</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rtm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Research team member</label>
            <code>rtm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/res</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Researcher</label>
            <code>res</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rsp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Respondent</label>
            <code>rsp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rst</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Respondent-appellant</label>
            <code>rst</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rse</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Respondent-appellee</label>
            <code>rse</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rpy</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Responsible party</label>
            <code>rpy</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rsg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Restager</label>
            <code>rsg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rev</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Reviewer</label>
            <code>rev</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/rbr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Rubricator</label>
            <code>rbr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sce</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Scenarist</label>
            <code>sce</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sad</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Scientific advisor</label>
            <code>sad</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/scr</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Scribe</label>
            <code>scr</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/scl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Sculptor</label>
            <code>scl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/spy</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Second party</label>
            <code>spy</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sec</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Secretary</label>
            <code>sec</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/std</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Set designer</label>
            <code>std</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sgn</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Signer</label>
            <code>sgn</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sng</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Singer</label>
            <code>sng</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sds</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Sound designer</label>
            <code>sds</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/spk</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Speaker</label>
            <code>spk</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/spn</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Sponsor</label>
            <code>spn</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/stm</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Stage manager</label>
            <code>stm</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/stn</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Standards body</label>
            <code>stn</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/str</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Stereotyper</label>
            <code>str</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/stl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Storyteller</label>
            <code>stl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/sht</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Supporting host</label>
            <code>sht</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/srv</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Surveyor</label>
            <code>srv</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/tch</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Teacher</label>
            <code>tch</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/tcd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Technical director</label>
            <code>tcd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/ths</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Thesis advisor</label>
            <code>ths</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/trc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Transcriber</label>
            <code>trc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/trl</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Translator</label>
            <code>trl</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/tyd</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Type designer</label>
            <code>tyd</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/tyg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Typographer</label>
            <code>tyg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/uvp</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>University place</label>
            <code>uvp</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/vdg</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Videographer</label>
            <code>vdg</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/voc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Vocalist</label>
            <code>voc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/wit</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Witness</label>
            <code>wit</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/wde</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Wood-engraver</label>
            <code>wde</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/wdc</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Woodcutter</label>
            <code>wdc</code>
         </role>
         <role>
            <uri>http://id.loc.gov/vocabulary/relators/wam</uri>
            <ns>http://id.loc.gov/vocabulary/relators/</ns>
            <label>Writer of accompanying material</label>
            <code>wam</code>
         </role>
      </roles>
   </xsl:variable>

   <xsl:function name="lib:role-code-to-uri" as="xs:string">
      <xsl:param name="code" as="xs:string?"/>
      <xsl:variable name="uri" as="xs:string?" select="$lib:role-lookup/roles/role[code eq $code]/uri"/>
      <xsl:choose>
         <xsl:when test="$uri">
            <xsl:value-of select="$uri"/>
         </xsl:when>
         <xsl:otherwise>http://id.loc.gov/vocabulary/relators/cre</xsl:otherwise>
      </xsl:choose>
   </xsl:function>
   
</xsl:stylesheet>
